name: ferrum
version: '1.0.0'
summary: A terminal for a modern age
description: |
  Ferrum is a local, SSH and serial terminal.

grade: devel
confinement: devmode

apps:
  ferrum:
    command: opt/ferrum/ferrum

parts:
  app:
    plugin: nodejs
    source: .
    build-packages:
      - libfontconfig-dev
    override-build: |
      yarn
      yarn run build
      ./scripts/build-linux.js
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/ferrum || true
      cp -ar dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/opt/ferrum/
